config/routes.rb
Rails.application.routes.draw do

  root "home#index"

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users
  resources :posts
  resources :comments
  resources :home
  resources :sessions

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
	has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  
 #  helper_method :current_user, :log_in

	def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    # return unless session[:user_id]
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @comments = Comment.all
    @post = Post.where(id: params[:post_id]).first
  end

  def show
    @comment = Comment.find(params[:id])
    @post = Post.where(id: @comment.post_id).first
  end

  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      flash[:notice] = "Comment has been created."
      redirect_to comment_path(@comment)
    else
      flash[:alert] = "problem!!! try again."
      redirect_to :back
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.delete
    redirect_to post_path
  end

  private

  def comment_params
  	params.require(:comment).permit(:id, :body, :user_id, :post_id, :comment)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @home = User.all
  end

  def show
    @home = Home.find(params[:id])
    @post = @user.posts
  end

  def new
  end

  def create
    @home = Home.create(user_params)

      if @user.save
        flash[:notice] = "Your account was created successfully."
        redirect_to new_user_path
      else
        flash[:alert] = "There was a problem saving your account."
        redirect_to new_user_path
      end

  end

  def update
  end

  def edit
  end

  def destroy
    session.clear
    redirect_to home_index_path
    flash[:alert] = "Bye Bye"
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :email)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all.reverse
  end

  def create
    current_user
  	@post = Post.new(post_params)
    @post.save
    redirect_to posts_path(@post)
  end

  def new
    current_user
    @post = Post.new
    @comment = Comment.new
  end

  def edit
  	@post = Post.find(params[:id])
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @comments = @post.comments.reverse
  end

  def update
  	@post = Post.find(params[:id])
  	@post.update(post_params)
  	redirect_to post_path(@post)
  end

  def destroy
  	@user = Post.destroy(params[:id])
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create 
  	user = User.find_by(email: params[:sessions][:email])

  	if user && user.password == (params[:sessions][:password])
  		log_in user
  		flash[:alert] = "you are signed in as #{current_user}"
  		redirect_to user
  	else
  		flash[:alert] = "wrong password or email"
  		render 'new'
  	end 	
  end

  def destroy
    redirect_to home_index_path
    flash[:alert] = "you are signed out"
  end

  private
  def user_params
    params.require(:user).permit(:username, :password, :email)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.reverse
  end

  def show
    @user = User.find(params[:id])
    @posts = Post.where(user_id: @user.id).reverse
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)

      if @user.save
        log_in @user
        flash[:notice] = "Your account was created successfully."
        redirect_to user_path(@user)
      else
        flash[:alert] = "There was a problem saving your account."
        redirect_to home_index_path
      end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "Updated successfully"
      redirect_to user_path(@user)
    else
      flash[:alert] = "Update failed"
      render :edit
    end
  end

  def destroy
    User.find(params[:id]).delete
    redirect_to users_path
    flash[:alert] = "Bye Bye"
  end

  private
  def user_params
    params.require(:user).permit(:username, :password, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in(user)
		session[:user_id] = user.id
	end

	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	def logged_in?
		!current_user.nil?
	end

	def log_out
		session.delete(:user_id)
		@current_user = nil
	end

end

app/helpers/users_helper.rb
module UsersHelper


end

app/views/comments/index.html.erb
<div id="anotherc">
<br>
	<h1>Comment!</h1>
	<% if logged_in? %>
		<%= form_for Comment.new do |f| %>
			<%=f.text_field :body %><br><br>
			<%=f.hidden_field :user_id, :value => @current_user.id %>
			<%= f.hidden_field :post_id, :value => @post.id %>
			<%=f.submit %>
		<% end %>
	<% end %>
	<br><br>
</div>

app/views/comments/show.html.erb
<div id="anotherco">
	<%= link_to("Delete", @comment, method: :delete) %> Comment<br>
	<%= link_to("Check out", post_path(@post)) %> your comment
</div>

app/views/home/index.html.erb
<div id='container'>
<br>
<h1>Welcome to Gawk</h1><br>

<h3> Write a post or comment on the trending image/topic of the day! </h3><br><hr>

<p><%= link_to "Signup", users_path %><br><br> to get started or<br><br><%= link_to "Login", sessions_path %><br><br> to start Gawking.</p><hr>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gawk</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= flash[:notice] if flash[:notice] %>
<%= flash[:alert] if flash[:alert] %>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<div id="zcontainer">
<br><br>
<%= form_for(@post) do |f| %>
	<%=f.label :title %>
	<%=f.text_field :title %><br><br>
	<%=f.label :body %>
	<%=f.text_field :body %><br><br>
	<%=f.submit "Update" %>
<% end %>
<p>or</p>

<%= link_to "Delete", post_path(@post), method: :delete%> post

<p>or just</p>

Go <%= link_to "Back ", :back %>
<br><br><br>
</div>

app/views/posts/index.html.erb
<div id="pcontainer">
	<br>
	<h1>Image of the Day!</h1><br>

	<div id="image1">
		<%= image_tag("turtle.jpg")%>
	</div><br><hr><br>

<h2>Errbody's Posts</h2><br>
		<% @posts.each do |post| %>
			<%= link_to post.title, post_path(post) %><br><br>
			<%= post.body %><br><br>
		<% end %><br>

	<hr><br>

	<h2>Post Something</h2>

	<% if logged_in? %>

		<%= form_for Post.new do |f| %>

			<%= f.label :title %>
			<br>
			<%= f.text_field :title %>
			<br>
			<%= f.label :body %>
			<br>
			<%= f.text_area :body %>
			<br><br>
			<%=f.hidden_field :user_id, :value => @current_user.id %>
			<%= f.submit %>

		<% end %><br><br><hr><br>

		<%= link_to "Go Back to Main Account", @current_user %>

	<% end %>
<br><br><br><br>
</div>

app/views/posts/show.html.erb
<div id='ccontainer'>
	<br><br>
	<h1><%= @post.title %></h1>
	<p><%= @post.body %></p><br><br>
	<%= link_to "Edit Post", edit_post_path %><br><br><hr>

	<h2>Comments on this Post</h2>
		<% @comments.each do |comment| %>
			<%= link_to comment.body, comment_path(comment) %><br><br>
			<%= comment.body %> <br><br>
		<% end %><br><br>

	<%= link_to "Comment on Post", comments_path(:post_id => @post.id) %><br>
	<br><hr><br>
	<%= link_to "Back to all Posts", posts_path %>
	<br><br><br>
</div>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<div id='ucontainer'>
<br>
<h1>Sign up</h1>

<%= form_for User.new do |f| %>
  <%=f.label :username %>
  <%=f.text_field :username %><br><br>
  <%=f.label :password %>
  <%=f.password_field :password %><br><br>
  <%=f.label :email %>
  <%=f.text_field :email %><br><br>
  <%=f.submit %><br><br>

<% end %><hr>

app/views/users/show.html.erb
<div id= 'mcontainer'>
<br>
<h1>Welcome <%= @user.username %>!</h1>
<%= link_to "Edit", edit_user_path %> your profile page!
<p>or</p>
<%= link_to "Gawk", posts_path %> at today's image!
<p>or</p>

<%= form_tag("/logout",method: "delete")do %> <%= submit_tag("Log Out") %>
<% end %><br><br>

</div>